name: Javadoc

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  javadoc:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate site
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/bvarner/shimaging-devcontainer
          runCmd: ./mvnw -B verify site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

